#!/bin/bash
#/ Usage: run VERSION...
#/ Specify at least two versions.

set -e
set -o nounset

cd "$(dirname "$0")"

main() {
  #rm -rf work
  mkdir -p work

  trap shutdown EXIT

  local start_cmd=start
  local version
  for version; do
    case "$version" in
      0.*)
        install_resqued "$version"
        $start_cmd
        push_job
        show_processes
        start_cmd=restart
        ;;
      *)
        echo "==> Sleeping $version"
        sleep "$version"
        show_processes
        ;;
    esac
  done
}

install_resqued() {
  local version="$1"
  echo "==> Installing resqued $version"
  cat > work/Gemfile <<EOF
source "https://rubygems.org"
gem "resqued", "${version}"
EOF
  (cd work && bundle --path .bundle --binstubs bin --quiet)
}

start() {
  echo "==> Starting resqued"
  work/bin/resqued --daemonize --pidfile work/resqued.pid ../basic/config.rb
  sleep 1
}

restart() {
  echo "==> Restarting resqued"
  kill -HUP "$(cat work/resqued.pid)"
  sleep 1
}

shutdown() {
  if [ -e work/resqued.pid ]; then
    echo "==> Stopping resqued"
    kill -QUIT "$(cat work/resqued.pid)" || true
    rm -f work/resqued.pid
    sleep 1
    show_processes
  fi
}

push_job() {
  echo "==> Pushing a 10s job [$(date)]"
  (cd work && bundle exec ruby ../../basic/push.rb 8)
  sleep 1
}

show_processes() {
  echo "==> Processes"
  date
  local psargs=
  if [ "$(uname -s)" = "Linux" ]; then
    psargs=-H
  fi
  ps axo pid,ppid,etime,args $psargs | grep [r]esque || true
}

main "$@"
